tempFolder: "tempFiles"

kafkaConsumer:
  topic: "files-to-scan-topic"
  partition: 0
  queueCapacity: 4
  groupId: "ToScanGroup"
  brokers: 
    - "127.0.0.1:9092"

kafkaProducer:
  addr: "127.0.0.1:9092"
  topic: "files-from-scan-topic"

clamavApi:
  uri: "http://host.docker.internal:8080/api/v1/scan"