maxSendFilesCount: 4
tickerDuration: 5
tempPostfix: "-temp"
scanFiles:
  uri: "http://localhost:8081/api/scan"
crashDb:
  sendToDb: false
  uri: http://Db
testDbRequest:
  uri: "http://localhost:8083/api/test"